import React from "react";
import { Layout } from "antd";
import "./Mangas.less";

import { Desktop, Mobile } from "../components/ScreenSize";
import PageLayout from "./PageLayout";

const { Content } = Layout;

const Mangas = () => {
  return (
    <PageLayout>
      <Desktop>
        <Content style={{ margin: "24px 16px 0", overflow: "initial" }}>
          <div className="site-layout-background" style={{ padding: 24, textAlign: "center" }}>
            ...
            <br />
            Really
            <br />
            ...
            <br />
            ...
            <br />
            ...
            <br />
            long
            <br />
            ...
            <br />
            ...
            <br />
            ...
            <br />
            ...
            <br />
            ...
            <br />
            ...
            <br />
            ...
            <br />
            ...
            <br />
            ...
            <br />
            ...
            <br />
            ...
            <br />
            ...
            <br />
            ...
            <br />
            ...
            <br />
            ...
            <br />
            ...
            <br />
            ...
            <br />
            ...
            <br />
            ...
            <br />
            ...
            <br />
            ...
            <br />
            ...
            <br />
            ...
            <br />
            ...
            <br />
            ...
            <br />
            ...
            <br />
            ...
            <br />
            ...
            <br />
            ...
            <br />
            ...
            <br />
            ...
            <br />
            ...
            <br />
            ...
            <br />
            ...
            <br />
            ...
            <br />
            ...
            <br />
            ...
            <br />
            ...
            <br />
            ...
            <br />
            ...
            <br />
            ...
            <br />
            content
          </div>
        </Content>
        <Content
          style={{
            width: 200,
            maxWidth: 200,
            overflow: "auto",
            height: "100vh",
            position: "fixed",
            right: 0,
            background: "blue",
          }}
        >
          HELLO
        </Content>
      </Desktop>
      <Mobile>MOBILE APP</Mobile>
    </PageLayout>
  );
};

export default Mangas;
