import React from "react";
import { Layout } from "antd";
import "./Mangas.less";

import { Desktop, Mobile } from "../components/ScreenSize";
import PageLayout from "./PageLayout";
import FAB from "../components/FAB";

const { Content } = Layout;

const Mangas = () => {
  return (
    <PageLayout>
      <Layout className="site-layout" style={{ marginRight: 200 }}>
        <Desktop>
          <Content style={{ margin: "24px 16px 0", overflow: "initial" }}>
            <div className="site-layout-background" style={{ padding: 24, textAlign: "center" }}>
              ...
              <br />
              Really
              <br />
              ...
              <br />
              ...
              <br />
              ...
              <br />
              long
              <br />
              ...
              <br />
              ...
              <br />
              ...
              <br />
              ...
              <br />
              ...
              <br />
              ...
              <br />
              ...
              <br />
              ...
              <br />
              ...
              <br />
              ...
              <br />
              ...
              <br />
              ...
              <br />
              ...
              <br />
              ...
              <br />
              ...
              <br />
              ...
              <br />
              ...
              <br />
              ...
              <br />
              ...
              <br />
              ...
              <br />
              ...
              <br />
              ...
              <br />
              ...
              <br />
              ...
              <br />
              ...
              <br />
              ...
              <br />
              ...
              <br />
              ...
              <br />
              ...
              <br />
              ...
              <br />
              ...
              <br />
              ...
              <br />
              ...
              <br />
              ...
              <br />
              ...
              <br />
              ...
              <br />
              ...
              <br />
              ...
              <br />
              ...
              <br />
              ...
              <br />
              ...
              <br />
              content
            </div>
          </Content>
          <Content
            style={{
              width: 200,
              maxWidth: 200,
              overflow: "auto",
              height: "100vh",
              position: "fixed",
              right: 0,
              background: "lightgrey",
            }}
          >
            HELLO
          </Content>
        </Desktop>
        <Mobile>MOBILE APP</Mobile>
        <FAB />
      </Layout>
    </PageLayout>
  );
};

export default Mangas;
